### ISSUE TITLE
[ROADMAP] Define a set of features we want before submitting to CRAN

### ISSUE THREAD

**Issue by mattcieslak** [PennLINC/FixelArray#13]
Make sure the package is in good shape before the initial submission to CRAN. 

TODO:
  - [ ] Set up automatic spell checking on the documentation
  - [ ] Set up automatic linting
  - [ ] Add authors and ORCIDs

Probably more too...
